import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next Project Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" flex justify-center items-center h-screen">
        <h1 className="text-red-800 text-7xl font-bold">
          Next Project Starter
        </h1>
      </div>
    </>
  )
}

export default Home
